CONTRIBUTING.md, README.md
</details> 
```yaml
```
</details>
By submitting this issue, you agree that report does not contain private info, also not in the screenshots
Dit issue bevat geen persoonlijke informatie, ook niet in de screenshots
=> Johny p36 patch 1

EasyDutch/Anti-Adblock.txt
`meerdangewenst.nl`
`meerdangewenst.nl##[class*="footer-section"]:has(.sponsoren):style(visibility: collapse !important;)` seems not necessary if `meerdangewenst.nl##[class*="footer-section"] > *:style(display: none !important;)` is enabled.
```yaml
_No input_
```
</details>
By submitting this issue, you agree that report does not contain private info, also not in the screenshots
Dit issue bevat geen persoonlijke informatie, ook niet in de screenshots
=> C: meerdangewenst.nl

EasyDutch/Anti-Adblock.txt
https://www.androidplanet.nl/tips/hoe-herken-ik-android-malware/ https://www.iphoned.nl/nieuws/iphone-correct-opladen-100-procent-capaciteit/
=> A: androidplanet.nl & iphoned.nl

EasyDutch/Block_Resources.txt
This breaks the complete site, not only the ads.
https://www.androidplanet.nl/nieuws/ovpay/
Door het blokkeren van `all.js` op androidplanet.nl en iphoned.nl werkt de hele site niet meer.
Dit is bijvoorbeeld te zien door het te proberen te gebruiken of door te proberen om in het gelinkte artikel de "vragen" open te klikken. 
Het normaal proberen te gebruiken van de website. Dat lukte niet. Daarna gekeken waarom het niet werkte. Ik zag in de browser dat `all.js` wordt geblokkeerd. Hierdoor werkt de complete site niet.
Disclaimer: ik werk voor BigSpark B.V., de organisatie achter AndroidPlanet.nl en iPhoned.nl dus ik heb er belang bij dat deze regel wordt weggehaald. Ik denk …
=> Remove the blocking of all.js for androidplanet.nl and iphoned.nl

EasyDutch/Block_Whitelist.txt
https://www.omroepbrabant.nl/nieuws/4201943/k3-avontuur-voor-diede-nu-echt-voorbij-eer-dat-ik-alsnog-de-kans-kreeg
https://www.omroepbrabant.nl/nieuws/4201943/k3-avontuur-voor-diede-nu-echt-voorbij-eer-dat-ik-alsnog-de-kans-kreeg
Can't play video
=> A: 2mdn.net on `omroepbrabant.nl`

EasyDutch/Hide_Specific.txt
loonwijzer.be
White blocks, because of blocked ads
=> A: loonwijzer.be

EasyDutch/Block_Resources.txt, EasyDutch/Hide_Specific.txt
https://diecourant.co.za/
See #41
=> Add South African sites

EasyDutch/Hide_Specific.txt
Multiple
Remove and change rules
</details> 
```yaml
```
</details>
=> Nomes77 remove

EasyDutch/Hide_Specific.txt
NSFW Farms
Delete NSFW Farms, since they are farms and often outdated.
End support, if there was any, for NSFW Farms
=> Removed Farms

EasyDutch/Block_Resources.txt, EasyDutch/Hide_Specific.txt
Different domains
Changed site code making rules outdated
=> Moved and checked some domains

EasyDutch/Anti-Adblock.txt, EasyDutch/Hide_Specific.txt
`https://www.moppen.nl/`
Anti-adblock
</details> 
=> A: moppen.nl

EasyDutch/Block_third_party_Server.txt, EasyDutch/Hide_Specific.txt
`bitcoinmagazine.nl` & `cryptobenelux.com`
See: `https://github.com/AdguardTeam/AdguardFilters/issues/163846`
</details> 
```yaml
```
</details>
=> A: & C: bitcoinmagazine.nl & cryptobenelux.com

EasyDutch/Block_Whitelist.txt, EasyDutch/Block_third_party_Server.txt
`mmcdn.nl` seems to block cookie popups and not ads, see: https://github.com/EasyDutch-uBO/EasyDutch/issues/61
=> R: `mmcdn.nl`

EasyDutch/Block_Whitelist.txt
Otherwise video on homepage would not load.
`www.bright.nl`
Section with videos would not load. 
</details> 
```yaml
```
</details>
=> A: ads.nextday.media on `bright.nl`

EasyDutch/Hide_Specific.txt
https://www.wijwedden.net/
https://www.wijwedden.net/artikelen/8485/verstappen-krijgt-steun-na-irritatie-over-de-boordradio-richting-lambiase/
=> A: wijwedden.net & gpfans.com

EasyDutch/Block_Resources.txt, EasyDutch/Hide_Specific.txt
=> A: Update rules

EasyDutch/Anti-Adblock.txt, EasyDutch/Block_Resources.txt, EasyDutch/Block_Whitelist.txt, EasyDutch/Block_third_party_Server.txt, EasyDutch/Hide_Specific.txt
Will be blocked by network request as code changed
nzbindex.nl
=> Update various sites

EasyDutch/Block_Resources.txt, EasyDutch/Hide_Specific.txt
https://www.ajaxfanatics.nl/
https://www.cambuurfront.nl/
https://www.feanonline.nl/
https://www.feyenoordpings.nl/
https://www.fcgfans.nl/
https://www.nacfans.nl/
https://www.psvfans.nl/
https://www.twentefans.nl/
https://www.utrechtfans.nl/
https://www.vitesseinside.nl/
https://www.voetbalverslaafd.nl/
https://www.vrouwenvoetbalnieuws.nl/
Betting popup and partner footer and unblocked element in right column.
</details> 
```yaml
```
</details>
By submitting this issue, you agree that this report does not contain private info, also not in the …
=> A: voetbal sites

EasyDutch/Block_Resources.txt, EasyDutch/Hide_Specific.txt
sun.sr
See https://github.com/EasyDutch-uBO/EasyDutch/issues/93
=> A: Ads on sun.sr

.github/workflows/main.yml, tools/easydutch-filters.template, tools/make-diffpatch.sh, tools/update-diffpatches.sh
Can be merged after uBlock Origin v1.53.1.4 is out.
See: https://github.com/uBlockOrigin/uAssets/discussions/20386#discussioncomment-7479098 & https://github.com/uBlockOrigin/uAssets/discussions/20386#discussioncomment-7467877
=> Remove `! Diff-Name:`

.github/workflows/main.yml, tools/easydutch-filters.template, tools/make-diffpatch.sh, tools/update-diffpatches.sh
Reverts EasyDutch-uBO/EasyDutch#91
=> Revert "Remove `! Diff-Name:`"

EasyDutch/Block_Resources.txt, EasyDutch/Hide_Specific.txt
`https://www.vpro.nl/argos/media/afleveringen/2020/uitzending-27-juni-ritueel-misbruik.html`
Ads in video
</details> 
```yaml
```
</details>
=> Nomes77 vpro

EasyDutch/Hide_Specific.txt
https://www.dumpert.nl/
Ad placeholders because of new lay-out.
=> C: dumpert.nl https://github.com/uBlockOrigin/uAssets/issues/21284

EasyDutch/Block_Resources.txt, EasyDutch/Hide_Specific.txt
https://github.com/EasyDutch-uBO/EasyDutch/issues/112 https://github.com/uBlockOrigin/uAssets/issues/20659 https://www.reddit.com/r/uBlockOrigin/comments/17tfadh/httpsnponlstartserieditwashetnieuws_doesnt_block/
https://www.bnnvara.nl/khalidensophie/videos/604650 https://npo.nl/start/serie/boer-zoekt-vrouw
https://npo.nl/start/serie/dit-was-het-nieuws
https://www.vpro.nl/argos/media/afleveringen/2020/uitzending-27-juni-ritueel-misbruik.html
=> C: bnnvara.nl, npo.nl, vpro.nl
